// Mocks generated by Mockito 5.4.2 from annotations
// in flutter_template/test/project_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:flutter_template/core/model/db/repository_db_entity.dart'
    as _i6;
import 'package:flutter_template/core/model/project.dart' as _i4;
import 'package:flutter_template/core/source/project_local_source.dart' as _i5;
import 'package:flutter_template/core/source/project_remote_source.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeStreamController_0<T> extends _i1.SmartFake
    implements _i2.StreamController<T> {
  _FakeStreamController_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProjectRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectRemoteSource extends _i1.Mock
    implements _i3.ProjectRemoteSource {
  MockProjectRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<List<_i4.Project>> getProjects() => (super.noSuchMethod(
        Invocation.method(
          #getProjects,
          [],
        ),
        returnValue: _i2.Future<List<_i4.Project>>.value(<_i4.Project>[]),
      ) as _i2.Future<List<_i4.Project>>);
}

/// A class which mocks [ProjectLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectLocalSource extends _i1.Mock
    implements _i5.ProjectLocalSource {
  MockProjectLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.StreamController<String> get changeListener => (super.noSuchMethod(
        Invocation.getter(#changeListener),
        returnValue: _FakeStreamController_0<String>(
          this,
          Invocation.getter(#changeListener),
        ),
      ) as _i2.StreamController<String>);
  @override
  set changeListener(_i2.StreamController<String>? _changeListener) =>
      super.noSuchMethod(
        Invocation.setter(
          #changeListener,
          _changeListener,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i2.Stream<List<_i6.ProjectDbEntity>> getProjects() => (super.noSuchMethod(
        Invocation.method(
          #getProjects,
          [],
        ),
        returnValue: _i2.Stream<List<_i6.ProjectDbEntity>>.empty(),
      ) as _i2.Stream<List<_i6.ProjectDbEntity>>);
  @override
  _i2.Future<void> insertProjects(List<_i6.ProjectDbEntity>? projects) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertProjects,
          [projects],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
  @override
  _i2.Future<void> deleteAllProjects() => (super.noSuchMethod(
        Invocation.method(
          #deleteAllProjects,
          [],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
  @override
  _i2.Future<void> replaceProjects(List<_i6.ProjectDbEntity>? projects) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceProjects,
          [projects],
        ),
        returnValue: _i2.Future<void>.value(),
        returnValueForMissingStub: _i2.Future<void>.value(),
      ) as _i2.Future<void>);
}
