# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
    - library_names
    - avoid_catching_errors
    - avoid_empty_else
    - avoid_returning_null
    - avoid_null_checks_in_equality_operators
    - empty_statements
    - unnecessary_parenthesis
    - unnecessary_this
    - unnecessary_const
    - unnecessary_overrides
    - unnecessary_brace_in_string_interps
    - lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures
    - slash_for_doc_comments

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.gen.dart'
  errors:
    invalid_annotation_target: ignore
