targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:

            - "lib/ui/**/cubit/*.dart" 
            - lib/ui/section/error_handler/general_error.dart
      auto_route_generator:
        generate_for:
          include:
            - "lib/ui/**_router.dart"  
            - "lib/ui/**_screen.dart"  
            - "lib/ui/**_section.dart"  
