targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
        generate_for:
          include:
          # Order matters for dependencies
            - "packages/models/lib/**.dart"
      freezed:
        generate_for:
          include:
          # Order matters for dependencies
            - "packages/models/lib/**.dart"
            - packages/services/src/networking/common/network_exceptions.dart    
            - "lib/ui/**/cubit/*.dart" 
            - lib/ui/section/error_handler/general_error.dart
      auto_route_generator:
        generate_for:
          include:
            - "lib/ui/**_router.dart"  
            - "lib/ui/**_screen.dart"  
            - "lib/ui/**_section.dart"  
