name: design_system
description: A new Flutter package project.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: 3.47.2

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^11.1.0
  flutter_screenutil: 5.9.3
  material_color_generator: 1.1.0
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  auto_route_generator: ^10.6.0
  flutter_gen_runner: ^5.15.0
  build_runner: ^2.16.1
  lints: ^6.1.0
