import "../../fastlane/Fastfile"

default_platform(:android)
platform :android do
  desc "**Generates a release apk**"
  desc "#### Envs\n" +
  " * **`env`**: Sets the env. It sets the flavour and the dart env. " +
  "The executed command is `build apk --flavor env --dart-define=ENV=env --debug`"
  lane :build_apk do |options|
    build_flutter(options.merge(build_platform: 'apk'))
  end

  desc "**Generates a release app bundle build**"
  desc "#### Envs\n" +
  " * **`env`**: Sets the env. It sets the flavour and the dart env. " +
  "The executed command is `flutter build appbundle --flavor env --dart-define=ENV=env --release`"
  lane :build_appbundle do |options|
    build_flutter(
      build_platform: 'appbundle',
      build_type: 'release',
    )
  end

  desc "**Build dev debug app**"
  lane :build_dev_debug_apk do |options|
    build_flutter(
      build_platform: 'apk',
      build_type: 'debug',
      env: ENV['APP_ENV'],
    )
  end

  desc "**Assemble prod apk release version**"
  lane :build_prod do
    build_apk(env: 'prod')
  end

  desc "**Assemble dev apk release version**"
  lane :build_dev do
    build_apk(env: 'staging')
    integration_test
  end

  desc "**Submit a new Beta Build to Firebase app distribution**"
  desc "#### Envs\n" +
  " * **`FIREBASE_APP_ID`**: Firebase app id.\n" +
  " * **`FIREBASE_SERVICE_ACCOUNT_FILE`**: The path to your Google service account json file.\n" +
  " * **`FIREBASE_TESTERS`**: The email addresses of the testers you want to invite.\n" +
  " You can specify the testers as a comma-separated list of email addresses: \"ali@example.com, bri@example.com, cal@example.com\"\n"
  " * **`FIREBASE_TESTER_GROUPS`**: The tester groups you want to invite." +
  " You can specify the groups as a comma-separated list: \"qa-team, trusted-testers\"\n"
  lane :deploy_firebase_app_distribution do |options|
    env = ENV['APP_ENV']
    clean
    build_apk(env: env, build_type: 'release', build_number: ENV['BUILD_NUMBER'])
    firebase_app_distribution(
      app: ENV['FIREBASE_APP_ID'],
      service_credentials_file: ENV["FIREBASE_SERVICE_ACCOUNT_FILE"],
      groups: ENV["FIREBASE_TESTER_GROUPS"],
      release_notes: generate_snapshot_changelog,
      apk_path: "../build/app/outputs/flutter-apk/app-#{env}-release.apk",
    )
  end

  desc "**Deploy a new version to the Google Play**"
  desc "#### Envs\n" +
  " * **`GOOGLE_PLAY_TRACK`**: Sets the release track. The default value is `internal`\n" +
  " * **`GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS_FILE`**: Sets the service account file.\n" +
  " * **`GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS_CONTENT`**: Sets the service account content file."
  lane :publish_prod_google_play do
    build_flutter(
      build_platform: 'appbundle',
      build_type: 'release',
      build_number: ENV.fetch('BUILD_NUMBER') { raise "BUILD_NUMBER is not set" },
      env: ENV['APP_ENV'],
    )

    upload_to_play_store(
      track: ENV['GOOGLE_PLAY_TRACK'] || 'internal',
      json_key: ENV['GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS_FILE'],
      json_key_data: ENV['GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS_CONTENT'],
      aab_paths: ["#{root_path}/build/app/outputs/bundle/prodRelease/app-prod-release.aab"],
    )
  end
end
